eureka:
    instance:
        preferIpAddress: true
        hostname: eureka-0
    client:
        serviceUrl:
            defaultZone: https://eureka-0.eureka.default.svc.cluster.local:8761/eureka
        registerWithEureka: true
        fetchRegistry: true
    level:
        org:
            springframework:
                cloud:
                    gateway: DEBUG
        reactor:
            netty:
                http:
                    client: DEBUG
server:
    port: 8765
    ssl:
        enabled: true
        key-alias: relevebancaire-docker
        key-store: classpath:relevebancaire-docker-keystore.p12
        key-store-password: secret
        key-store-type: PKCS12
spring:
    sleuth:
        sampler:
            probability: 1.0
    application:
        name: api-gateway
    cloud:
        config:
            enabled: false
        gateway:
            discovery:
                locator:
                    enabled: true
            httpclient:
                wiretap: true
            httpserver:
                wiretap: true
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "https://localhost:4200"
                        allowedHeaders: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
ribbon:
    secure-ports: 8081,8082,8083,8765,8761
